### ISSUE TITLE
Version 5.0.0 Loadup crash

### ISSUE THREAD

**Issue by OS-Void** [The-Fireplace-Minecraft-Mods/Grand-Economy#33]
**Logs**

```
[21:44:05] [Render thread/ERROR]: Exception when reading implementation file!
java.lang.ClassNotFoundException: dev.the_fireplace.grandeconomy.api.injectables.CurrencyAPI
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175) ~[fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at dev.the_fireplace.annotateddi.impl.di.AnnotatedDIModule.stringToClass(AnnotatedDIModule.java:187) ~[48ea8e76-26c7-4370-8bd2-9d3a118a235d.jar:?]
	at dev.the_fireplace.annotateddi.impl.di.AnnotatedDIModule.readImplementationContainerJson(AnnotatedDIModule.java:142) ~[48ea8e76-26c7-4370-8bd2-9d3a118a235d.jar:?]
	at dev.the_fireplace.annotateddi.impl.di.AnnotatedDIModule.readImplementationContainerFromPath(AnnotatedDIModule.java:121) ~[48ea8e76-26c7-4370-8bd2-9d3a118a235d.jar:?]
	at dev.the_fireplace.annotateddi.impl.di.AnnotatedDIModule.getImplementationContainersFromConfigs(AnnotatedDIModule.java:103) ~[48ea8e76-26c7-4370-8bd2-9d3a118a235d.jar:?]
	at dev.the_fireplace.annotateddi.impl.di.AnnotatedDIModule.findImplementations(AnnotatedDIModule.java:52) ~[48ea8e76-26c7-4370-8bd2-9d3a118a235d.jar:?]
	at dev.the_fireplace.annotateddi.impl.di.AnnotatedDIModule.configure(AnnotatedDIModule.java:31) ~[48ea8e76-26c7-4370-8bd2-9d3a118a235d.jar:?]
	at com.google.inject.AbstractModule.configure(AbstractModule.java:64) ~[80864e15-c37d-4d33-9d00-6bef7c2e8456.jar:?]
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409) ~[80864e15-c37d-4d33-9d00-6bef7c2e8456.jar:?]
	at com.google.inject.spi.Elements.getElements(Elements.java:108) ~[80864e15-c37d-4d33-9d00-6bef7c2e8456.jar:?]
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:160) ~[80864e15-c37d-4d33-9d00-6bef7c2e8456.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[80864e15-c37d-4d33-9d00-6bef7c2e8456.jar:?]
	at com.google.inject.Guice.createInjector(Guice.java:87) ~[80864e15-c37d-4d33-9d00-6bef7c2e8456.jar:?]
	at com.google.inject.Guice.createInjector(Guice.java:78) ~[80864e15-c37d-4d33-9d00-6bef7c2e8456.jar:?]
	at dev.the_fireplace.annotateddi.impl.AnnotatedDI.getInjector(AnnotatedDI.java:33) ~[48ea8e76-26c7-4370-8bd2-9d3a118a235d.jar:?]
	at dev.the_fireplace.annotateddi.api.DIContainer.get(DIContainer.java:8) ~[48ea8e76-26c7-4370-8bd2-9d3a118a235d.jar:?]
	at dev.the_fireplace.annotateddi.impl.AnnotatedDI.onInitialize(AnnotatedDI.java:41) ~[48ea8e76-26c7-4370-8bd2-9d3a118a235d.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33) [fabric-loader-0.11.6.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:457) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:179) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```
```
[21:28:09] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'annotateddi'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric-server-launch.jar:?]
	at net.minecraft.server.Main.main(MixinMain.java:97) [intermediary-server.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
Caused by: java.lang.NoClassDefFoundError: dev/the_fireplace/grandeconomy/api/injectables/CurrencyAPI
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:170) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at dev.the_fireplace.grandeconomy.entrypoints.MainEntrypoint.onInitialize(MainEntrypoint.java:22) ~[GrandEconomy-5.0.0+1.17.1.jar:?]
	at dev.the_fireplace.annotateddi.impl.AnnotatedDI.lambda$onInitialize$1(AnnotatedDI.java:43) ~[9ccf6394-c131-4a48-8cc3-7926c9212fa6.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at dev.the_fireplace.annotateddi.impl.AnnotatedDI.onInitialize(AnnotatedDI.java:43) ~[9ccf6394-c131-4a48-8cc3-7926c9212fa6.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
	... 17 more
Caused by: java.lang.ClassNotFoundException: dev.the_fireplace.grandeconomy.api.injectables.CurrencyAPI
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:57) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:170) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at dev.the_fireplace.grandeconomy.entrypoints.MainEntrypoint.onInitialize(MainEntrypoint.java:22) ~[GrandEconomy-5.0.0+1.17.1.jar:?]
	at dev.the_fireplace.annotateddi.impl.AnnotatedDI.lambda$onInitialize$1(AnnotatedDI.java:43) ~[9ccf6394-c131-4a48-8cc3-7926c9212fa6.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at dev.the_fireplace.annotateddi.impl.AnnotatedDI.onInitialize(AnnotatedDI.java:43) ~[9ccf6394-c131-4a48-8cc3-7926c9212fa6.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
	... 17 more
```

**Versions**
 - Minecraft: 1.17.1
 - Mod Version: 5.0.0
 - Fireplace Lib: 5.3.0
 - Fabric API: 0.37.1

**Comment by The-Fireplace** [comment]
Thanks for the quick report. Fixing it now with GE 5.0.1, it should be released in a few minutes.
