### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by anthonydeaver** [The-Fireplace-Minecraft-Mods/Grand-Economy#42]
### Mod Version

6.0.0

### What mod loader(s) are you seeing the problem on?

Fabric

### Mod Loader Version

0.14.9

### Problem Description

Server crashs

### Steps To Reproduce

All I did was drop FireplaceLIb and GrandEconomy in the mods folder and start the server using this `java -Xms512m -Xmx2G -jar fabric-server-mc.1.19.2-loader.0.14.9-launcher.0.11.1.jar nogui`

### Crash Report or Error Logs

```shell
java.lang.ClassCastException: class net.minecraft.class_2186 cannot be cast to class dev.the_fireplace.lib.api.command.interfaces.OfflineSupportedPlayerArgumentType (net.minecraft.class_2186 and dev.the_fireplace.lib.api.command.interfaces.OfflineSupportedPlayerArgumentType are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @77caeb3e)
	at dev.the_fireplace.lib.command.helpers.ArgumentTypeFactoryImpl.possiblyOfflinePlayer(ArgumentTypeFactoryImpl.java:26)
	at dev.the_fireplace.grandeconomy.command.commands.PayCommand.register(PayCommand.java:40)
	at dev.the_fireplace.grandeconomy.command.RegisterGeCommands.register(RegisterGeCommands.java:46)
	at dev.the_fireplace.grandeconomy.entrypoints.Main.lambda$onInitialize$1(Main.java:28)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:38)
	at net.minecraft.server.MinecraftServer.handler$zdc000$beforeSetupServer(MinecraftServer.java:2796)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Additional Information

diamondeconomy 1.5.4
Luckperms 5.4.52
Fabric API 0.62.0
cloth config 8.2.88
skylands 0.1.1

I have the crash report if that helps: https://pastebin.com/7K6Yt9DT

**Comment by anthonydeaver** [comment]
Just updated, crash resolved. Thanks!
